### ISSUE TITLE
Adding the ToF support

### ISSUE THREAD

**Issue by Gheim2** [STMicroelectronics/b-l4s5i-iot01a#2]
In this board there is also a VL53L0X Time of Flight sensor. An example of how to use that would be really useful and a good enhancement to this repo.

**Comment by ASEHSTM** [comment]
Hello @Gheim2,

Thank you for your contribution. You can find an example for the VL53L0X developed for the B-L475E-IOT01A [here](https://github.com/STMicroelectronics/STM32CubeL4/tree/master/Projects/B-L475E-IOT01A/Applications/Proximity).

With Regards,

**Comment by ASEHSTM** [comment]
Hello @Gheim2,

Please allow me to close this thread and please note that the example I have provided exists in the CubeFW repository and this repository is intended to contain only the driver for the B-L475E-IOT01A board.

With Regards,
